# Generated by Django 5.0.2 on 2024-05-02 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
