# Generated by Django 5.0.2 on 2024-05-02 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_discount_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='quantities',
        ),
    ]
